# Generated by Django 4.2.7 on 2024-01-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_englishoptional_englishoptionalnumber1_and_more'),
        ('api', '0002_englishword'),
    ]

    operations = [
    ]
