# Generated by Django 4.2.7 on 2023-12-20 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20231216_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWordSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('phonetic_symbols', models.TextField()),
                ('part_of_speech', models.TextField()),
                ('explain', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='student_scores',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
