# Generated by Django 4.2.7 on 2023-12-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_englishwordsearch_student_scores_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_scores',
            new_name='StudentScores',
        ),
    ]
