# Generated by Django 4.2.7 on 2023-12-30 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_student_scores_studentscores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishword',
            name='phonetic_symbols',
        ),
    ]
